language: python

python:
  - "3.8"

install:
  - git submodule update --init --recursive
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --quiet conda
  - conda info --all
  - conda env create --quiet --name xstate --file environment.yml
  - source activate xstate
  - pip install --upgrade pip
  - conda install -c anaconda nose requests scipy seaborn
  - pip install matplotlib numpy pandas nose pyyaml
  - pip install sklearn scipy seaborn

script:
  - PYTHONPATH="`pwd`/xstate/python:`pwd`/common_python"
  - export PYTHONPATH
  - nosetests xstate/python/tests
