language: python

python:
  - "3.8"

install:
  - git submodule update --init --recursive
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda info --all
  - conda update -q conda

script:
  - conda env create -q -n test-environment --file environment.yml
  - conda activate test-environment
  - PYTHONPATH="`pwd`/xstate/python:`pwd`/common_python"
  - export PYTHONPATH
  - nosetests xstate/python/tests
