channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pandas
  - python
  - requests
  - matplotlib
  - nose
  - seaborn
  - scipy
  - graphviz
  - scikit-learn
  - seaborn
  - notebook
  - sip
  - xlrd
