channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pandas
  - python
  - requests
  - matplotlib
  - nose
  - seaborn
  - scipy
  - graphviz
  - scikit-learn=0.22.1
  - seaborn
  - notebook
  - sip
  - xlrd
